name: "Merge into Main"

on:
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo a message
        run: echo "I'm running a pipeline that is triggerd by a push event to main!"
