name: "Open Pull Request into Main"

on:
  pull_request:
    branches:
      - main

jobs:
  pr-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo a message
        run: echo "I'm running a pipeline that is triggerd by a PR open to main!"